const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('player.js','utf8');
function fn(name){const start=src.indexOf('  function '+name+'(');return src.slice(start,src.indexOf('\n  }',start)+4)}
test('old cache without authorization cannot play offline',()=>{const c=vm.createContext({state:{manifest:{device:{}}},Date});vm.runInContext(fn('localAccessExpired'),c);assert.equal(c.localAccessExpired(),true)});
test('invalid offline deadline fails closed',()=>{const c=vm.createContext({state:{manifest:{device:{access_expires_at:'invalid'}}},Date});vm.runInContext(fn('localAccessExpired'),c);assert.equal(c.localAccessExpired(),true)});
test('valid offline lease permits playback until its boundary',()=>{let now=10000;const c=vm.createContext({state:{manifest:{device:{access_expires_at:new Date(11000).toISOString()}}},Date:class extends Date{static now(){return now}}});vm.runInContext(fn('localAccessExpired'),c);assert.equal(c.localAccessExpired(),false);now=11000;assert.equal(c.localAccessExpired(),true)});
test('expired authorization cannot start the playback loop',()=>{let starts=0;const c=vm.createContext({state:{running:false},enforceLocalAccess:()=>true,playbackLoop:()=>{starts++;return Promise.resolve()},console});vm.runInContext(fn('ensurePlaybackLoop'),c);c.ensurePlaybackLoop();assert.equal(starts,0)});
const gateway=fs.readFileSync('supabase/functions/device-gateway/index.ts','utf8');
function gatewayFn(name){const start=gateway.indexOf('function '+name+'(');assert.ok(start>=0,name+' missing');return gateway.slice(start,gateway.indexOf('\n}',start)+2)}
test('server limits offline permission to paid deadline or 24 hours',()=>{const c=vm.createContext({Date});vm.runInContext(gatewayFn('offlineAccessDeadline'),c);const now=Date.parse('2026-10-08T19:00:00Z');assert.equal(c.offlineAccessDeadline({access_expires_at:null},{status:'active',current_period_end:'2026-10-08T20:00:00Z'},now),'2026-10-08T20:00:00.000Z');assert.equal(c.offlineAccessDeadline({}, {status:'active',current_period_end:null},now),'2026-10-09T19:00:00.000Z');assert.equal(c.offlineAccessDeadline({}, {status:'trialing',trial_ends_at:'2026-10-08T19:30:00Z'},now),'2026-10-08T19:30:00.000Z')});
test('test without a deadline is blocked by server',()=>{const c=vm.createContext({Date});vm.runInContext(gatewayFn('accountSubscriptionBlock'),c);assert.equal(c.accountSubscriptionBlock({status:'active'},{status:'trialing',trial_ends_at:null}).reason,'trial_expired')});
test('server denial removes reusable saved permission',()=>{let saved='old';const nodes=new Map();const state={manifest:{device:{access_expires_at:'2099-01-01'}},playlistNonce:0};const c=vm.createContext({state,Date,MANIFEST_KEY:'m',writeJson:(k,v)=>saved=v,clearCurrentObjectUrl(){},replaceNodeChildren(){},$:s=>{if(!nodes.has(s))nodes.set(s,{classList:{add(){},remove(){}}});return nodes.get(s)}});vm.runInContext(fn('showAccessBlocked'),c);c.showAccessBlocked({error:'account_suspended',reason:'subscription_expired'});assert.equal(saved,null);assert.equal(state.manifest,null)});
