const{test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
async function boot({storage=new Map(),standalone=false,related,ios=false,date='2026-10-09T12:00:00',blocked=false}={}){
 const events={},cards=[],parts=new Map();let now=new Date(date);const localStorage={getItem:k=>{if(blocked)throw Error('blocked');return storage.get(k)??null;},setItem:(k,v)=>{if(blocked)throw Error('blocked');storage.set(k,v);},removeItem:k=>storage.delete(k)};
 const document={referrer:'',visibilityState:'visible',body:{append:e=>cards.push(e)},addEventListener(k,fn){events['doc:'+k]=fn;},querySelector(){return null;},createElement(){return{setAttribute(){},remove(){this.removed=true;},querySelector(k){if(!parts.has(k))parts.set(k,{});return parts.get(k);}}}};
 const navigator={userAgent:ios?'iPhone':'Android',standalone,maxTouchPoints:0};if(related!==undefined)navigator.getInstalledRelatedApps=async()=>related;
 const window={top:null,self:null,matchMedia:()=>({matches:standalone,addEventListener(){}}),addEventListener(k,fn){events[k]=fn;}};window.top=window.self=window;
 vm.runInNewContext(fs.readFileSync('pwa-install.js','utf8'),{window,document,navigator,localStorage,location:{origin:'https://example.test'},URL,Date:class extends Date{constructor(...a){super(...(a.length?a:[now]));}},setTimeout:fn=>{fn();return 1;},clearTimeout(){}});
 await new Promise(r=>setImmediate(r));return{cards,parts,events,storage,async offer(){const e={preventDefault(){},prompt:async()=>{},userChoice:Promise.resolve({outcome:'dismissed'})};await events.beforeinstallprompt(e);await new Promise(r=>setImmediate(r));return e;}};
}
test('install invitation shows once a day across page reloads',async()=>{const storage=new Map();const a=await boot({storage});await a.offer();assert.equal(a.cards.length,1);a.parts.get('[data-dismiss]').onclick();const b=await boot({storage});await b.offer();assert.equal(b.cards.length,0);const c=await boot({storage,date:'2026-10-10T00:01:00'});await c.offer();assert.equal(c.cards.length,1);});
test('installed launch never promotes installation',async()=>{const a=await boot({standalone:true});assert.equal(a.cards.length,0);assert.equal(a.storage.get('vision_pwa_installed_v1'),'1');});
test('related installed PWA suppresses browser invitation',async()=>{const a=await boot({related:[{platform:'webapp',url:'https://example.test/manifest.webmanifest'}]});assert.equal(a.cards.length,0);});
test('installation completion removes banner and persists installed state',async()=>{const a=await boot();await a.offer();a.events.appinstalled();assert.equal(a.cards[0].removed,true);assert.equal(a.storage.get('vision_pwa_installed_v1'),'1');});
test('confirmed new install opportunity clears stale installed marker',async()=>{const storage=new Map([['vision_pwa_installed_v1','1']]);const a=await boot({storage});await a.offer();assert.equal(a.cards.length,1);assert.equal(storage.has('vision_pwa_installed_v1'),false);});
test('iPhone invitation provides manual install instructions and remember-installed action',async()=>{const a=await boot({ios:true});assert.equal(a.cards.length,1);await a.parts.get('[data-install]').onclick();assert.match(a.parts.get('[data-message]').textContent,/Compartilhar.*Tela de Início/);a.parts.get('[data-installed]').onclick();assert.equal(a.cards[0].removed,true);});
test('blocked local storage does not crash installation flow',async()=>{const a=await boot({blocked:true});await a.offer();assert.equal(a.cards.length,1);});
test('Android without native install API gets usable browser-menu instructions',async()=>{const a=await boot();assert.equal(a.cards.length,1);await a.parts.get('[data-install]').onclick();assert.match(a.parts.get('[data-message]').textContent,/menu.*Instalar aplicativo/);});
