const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs');
let core;
const load=()=>core||=import('../lib/pwa-icon-core.mjs');
const icons=()=>Object.fromEntries([['192','vision-192.png'],['512','vision-512.png'],['maskable','vision-maskable-512.png']].map(([k,n])=>[k,fs.readFileSync('icons/'+n).toString('base64')]));
function store(){const data=new Map();let serial=0;return {data,async get(k){return data.get(k)?.data??null;},async getWithMetadata(k){return data.has(k)?data.get(k):null;},async setJSON(k,v,opts={}){const old=data.get(k);if((opts.onlyIfNew&&old)||(opts.onlyIfMatch&&old?.etag!==opts.onlyIfMatch))return{modified:false};const etag=String(++serial);data.set(k,{data:structuredClone(v),etag});return{modified:true,etag};}};}
function req(body,token='valid'){return new Request('https://example.test/api/app-icon',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',Origin:'https://example.test'},body:JSON.stringify(body)});}
async function handler(role='super_admin'){const m=await load();const s=store();return {s,run:m.createHandler({getStore:()=>s,authorize:async t=>t==='valid'?role:null})};}
test('manifest keeps identity and default chosen logo',async()=>{const {run}=await handler();const r=await run(new Request('https://example.test/manifest.webmanifest'));const m=await r.json();assert.equal(m.start_url,'./');assert.equal(m.scope,'./');assert.equal(m.display,'standalone');assert.equal(m.icons[1].src,'/icons/vision-512.png?v=20261009');assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(m.related_applications[0].id,'https://example.test/');assert.equal(m.related_applications[0].url,'./manifest.webmanifest');assert.equal(m.prefer_related_applications,false);});
test('invalid session cannot replace icon',async()=>{const {s,run}=await handler();assert.equal((await run(req({icons:icons()},'invalid'))).status,403);assert.equal(s.data.size,0);});
test('read-only Master cannot replace global icon',async()=>{const {s,run}=await handler('support');assert.equal((await run(req({icons:icons()}))).status,403);assert.equal(s.data.size,0);});
test('wrong PNG or dimensions leave current icon intact',async()=>{const {s,run}=await handler();const body=icons();body['192']=body['512'];assert.equal((await run(req({icons:body}))).status,400);assert.equal(s.data.size,0);});
test('atomic save publishes immutable revision; old image remains available',async()=>{const {run}=await handler();const a=await (await run(req({icons:icons(),expected_revision:null}))).json();assert.ok(a.revision);let m=await (await run(new Request('https://example.test/manifest.webmanifest'))).json();assert.match(m.icons[1].src,new RegExp(a.revision));const old=m.icons[1].src;await run(req({icons:icons(),expected_revision:a.revision}));const asset=await run(new Request('https://example.test'+old));assert.equal(asset.status,200);assert.equal(asset.headers.get('content-type'),'image/png');assert.match(asset.headers.get('cache-control'),/immutable/);});
test('stale writer receives conflict without replacing published revision',async()=>{const {run}=await handler();const a=await (await run(req({icons:icons(),expected_revision:null}))).json();assert.equal((await run(req({icons:icons(),expected_revision:null}))).status,409);const current=await (await run(new Request('https://example.test/app-icon-config'))).json();assert.equal(current.revision,a.revision);});
test('cross-origin writes rejected before persistence',async()=>{const {s,run}=await handler();const r=req({icons:icons()});r.headers.set('origin','https://evil.test');assert.equal((await run(r)).status,403);assert.equal(s.data.size,0);});
