plugins {
    id 'com.android.application'
}

android {
    namespace 'com.visionmidia.player'
    compileSdk 35

    defaultConfig {
        applicationId 'com.visionmidia.player'
        minSdk 24
        targetSdk 35
        versionCode 19
        versionName '1.5.7'
        manifestPlaceholders = [playerLabel: 'Vision Player', setupScheme: 'visionmidia']
    }

    buildTypes {
        debug {
            versionNameSuffix '-preview'
        }
        release {
            applicationIdSuffix '.stable'
            versionNameSuffix '-stable'
            manifestPlaceholders = [playerLabel: 'Vision Player Estável', setupScheme: 'visionmidia-stable']
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
